In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import read_csv
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from keras.layers.core import Dense, Activation, Dropout
import time  # helper libraries

In [2]:
from dataset_window import Dataset


def convertCash(cash):
	cash = cash.replace('.', '')
	cash = cash.replace(',', '.')
	return float(cash)


def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back), :]
		dataX.append(a)
		dataY.append(dataset[i + look_back, :])
		# print(dataY)
		# exit(1)
	return np.array(dataX), np.array(dataY)

In [3]:
#Carregando os dados
data = pd.read_csv("onion_price2.csv", parse_dates=['Mês'])
data.set_index('Mês', inplace=True)

data['Preço'] = data['Preço'].apply(convertCash)
data['PREÇO_DOLAR'] = data['PREÇO_DOLAR'].apply(convertCash)

x, y = create_dataset(data.values, 4)
print(x)
print(y)
# print(dataset.windowed_dataset())
exit(1)

[[[53.2     3.9988]
  [56.5     4.0171]
  [54.      3.5935]
  [46.4     3.4358]]

 [[56.5     4.0171]
  [54.      3.5935]
  [46.4     3.4358]
  [50.      3.6111]]

 [[54.      3.5935]
  [46.4     3.4358]
  [50.      3.6111]
  [25.8     3.2134]]

 [[46.4     3.4358]
  [50.      3.6111]
  [25.8     3.2134]
  [12.75    3.2486]]

 [[50.      3.6111]
  [25.8     3.2134]
  [12.75    3.2486]
  [13.      3.2273]]

 [[25.8     3.2134]
  [12.75    3.2486]
  [13.      3.2273]
  [13.25    3.2603]]

 [[12.75    3.2486]
  [13.      3.2273]
  [13.25    3.2603]
  [ 6.13    3.1893]]

 [[13.      3.2273]
  [13.25    3.2603]
  [ 6.13    3.1893]
  [13.      3.3842]]

 [[13.25    3.2603]
  [ 6.13    3.1893]
  [13.      3.3842]
  [17.5     3.2547]]

 [[ 6.13    3.1893]
  [13.      3.3842]
  [17.5     3.2547]
  [20.5     3.1509]]

 [[13.      3.3842]
  [17.5     3.2547]
  [20.5     3.1509]
  [28.      3.1091]]

 [[17.5     3.2547]
  [20.5     3.1509]
  [28.      3.1091]
  [24.      3.1233]]

 [[20.5     3.15